name: pkg releases
on:
  push:
    branches-ignore:
      - latest
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Tags
        id: tags
        uses: livepeer/action-gh-release-tags@v0

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: build pkgs
        run: |
          yarn run lerna-run pkg --parallel

      - name: move pkgs
        run: |
          mkdir -p ./pkg-releases
          for package in api www; do
            for arch in linux-arm64 linux-x64 macos-arm64 macos-x64 win-x64; do
              name="$package-$arch"
              if [[ "$arch" == "win-x64" ]]; then
                name="$name.exe"
              fi
              cd ./packages/$package/bin
              tar -czvf ./livepeer-$package-$arch.tar.gz ../../../pkg-releases/livepeer-$name
              cd -
            done
          done

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pkg-releases
          path: |
            ./pkg-releases/*.tar.gz
