name: pkg releases
on:
  push:
    branches-ignore:
      - latest
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Tags
        id: tags
        uses: livepeer/action-gh-release-tags@v0

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: build pkgs
        # I want to do --parallel here, but the binary downloads conflict with each other
        run: |
          yarn run lerna-run pkg

      - name: move pkgs
        run: |
          mkdir -p ./pkg-releases
          for package in api www; do
            for arch in linux-arm64 linux-x64 macos-arm64 macos-x64 win-x64; do
              inName="$package-$arch"
              outName="livepeer-$package"
              archiveName="livepeer-$(echo $inName | sed s/x64/amd64/ | sed s/win/windows/ | sed s/macos/darwin/).tar.gz"
              if [[ "$arch" == "win-x64" ]]; then
                inName="$inName.exe"
                outName="$outName.exe"
              fi
              cd ./packages/$package/bin
              mv ./$inName ./$outName
              tar -czvf ../../../pkg-releases/$archiveName ./$outName
              cd -
            done
          done

      # This is a proof-of-concept, we're going to want something a bit more elegant
      - name: archive livepeer-api-linux-arm64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-linux-arm64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-linux-arm64.tar.gz

      - name: archive livepeer-api-linux-amd64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-linux-amd64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-linux-amd64.tar.gz

      - name: archive livepeer-api-darwin-arm64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-darwin-arm64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-darwin-arm64.tar.gz

      - name: archive livepeer-api-darwin-amd64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-darwin-amd64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-darwin-amd64.tar.gz

      - name: archive livepeer-api-windows-amd64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-windows-amd64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-windows-amd64.tar.gz

      - name: archive livepeer-www-linux-arm64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-linux-arm64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-linux-arm64.tar.gz

      - name: archive livepeer-www-linux-amd64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-linux-amd64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-linux-amd64.tar.gz

      - name: archive livepeer-www-darwin-arm64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-darwin-arm64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-darwin-arm64.tar.gz

      - name: archive livepeer-www-darwin-amd64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-darwin-amd64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-darwin-amd64.tar.gz

      - name: archive livepeer-www-windows-amd64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-windows-amd64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-windows-amd64.tar.gz
