name: pkg releases
on:
  push:
    branches-ignore:
      - latest
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Tags
        id: tags
        uses: livepeer/action-gh-release-tags@v0

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: build pkgs
        # I want to do --parallel here, but the binary downloads conflict with each other
        run: |
          yarn run lerna-run pkg

      - name: move pkgs
        run: |
          mkdir -p ./pkg-releases
          for package in api www; do
            for arch in linux-arm64 linux-x64 macos-arm64 macos-x64 win-x64; do
              name="$package-$arch"
              if [[ "$arch" == "win-x64" ]]; then
                name="$name.exe"
              fi
              cd ./packages/$package/bin
              mv ./$name ./livepeer-$name
              tar -czvf ../../../pkg-releases/livepeer-$package-$arch.tar.gz ./livepeer-$name
              cd -
            done
          done

      # This is a proof-of-concept, we're going to want something a bit more elegant
      - name: archive livepeer-api-linux-arm64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-linux-arm64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-linux-arm64.tar.gz

      - name: archive livepeer-api-linux-x64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-linux-x64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-linux-x64.tar.gz

      - name: archive livepeer-api-macos-arm64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-macos-arm64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-macos-arm64.tar.gz

      - name: archive livepeer-api-macos-x64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-macos-x64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-macos-x64.tar.gz

      - name: archive livepeer-api-win-x64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-win-x64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-win-x64.tar.gz

      - name: archive livepeer-www-linux-arm64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-linux-arm64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-linux-arm64.tar.gz

      - name: archive livepeer-www-linux-x64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-linux-x64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-linux-x64.tar.gz

      - name: archive livepeer-www-macos-arm64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-macos-arm64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-macos-arm64.tar.gz

      - name: archive livepeer-www-macos-x64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-macos-x64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-macos-x64.tar.gz

      - name: archive livepeer-www-win-x64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-www-win-x64.tar.gz
          path: |
            ./pkg-releases/livepeer-www-win-x64.tar.gz
